#!/usr/bin/env php
<?php

use Webgraphe\Phlip\Tests\PhlipScriptTestSuite;

require_once 'vendor/autoload.php';

function fatalError($message)
{
    echo trim($message) . PHP_EOL . PHP_EOL;
    exit(1);
}

$paths = [];
$arguments = $_SERVER['argv'];
array_shift($arguments);
foreach ($arguments as $argument) {
    if (0 === strpos($argument, '--')) {
        // TODO Implement options support
    } else {
        $paths[] = $argument;
    }
}

if (empty($paths)) {
    fatalError("No Test.phlip files to run");
}

\PHPUnit\TextUI\TestRunner::run(new PhlipScriptTestSuite($paths), ['colors' => 'always']);
