#!/usr/bin/env php
<?php

namespace Webgraphe\Phlip;

require_once 'vendor/autoload.php';

$context = Phlipy::withRepl(Phlipy::context(), Phlipy::optionsFromGlobals());

try {
    // Phlip script injected from the input
    if (false !== ftell(STDIN)) {
        $script = trim(file_get_contents('php://stdin'));
        $result = Program::parse($script)->execute($context);
        $context = $context->stack();
        $context->let('result', $result);
        Program::parse('(print result)')->execute($context);

        exit(0);
    }

    // Interactive REPL prompt
    echo 'Webgraphe Phlip REPL prompt' . PHP_EOL;
    echo "Type (exit) to quit." . PHP_EOL . PHP_EOL;
    Program::parse('(loop (print (eval (read))))')->execute($context);
} catch (\Throwable $exception) {
    echo "FATAL ERROR: " . $exception->getMessage() . PHP_EOL . PHP_EOL;
}
