#!/usr/bin/env php
<?php

use Webgraphe\Phlip\Tests\PhlipScriptTestSuite;

$autoloadFiles = [__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'];
foreach ($autoloadFiles as $autoloadFile) {
    if (file_exists($autoloadFile)) {
        define('PHLIP_AUTOLOAD_FILE', $autoloadFile);
        break;
    }
}
unset($autoloadFile);
if (!defined('PHLIP_AUTOLOAD_FILE')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL
        . PHP_EOL
        . '    composer install' . PHP_EOL
        . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );
    die(1);
}
require PHLIP_AUTOLOAD_FILE;

function fatalError($message)
{
    echo trim($message) . PHP_EOL . PHP_EOL;
    exit(1);
}

$paths = [];
$arguments = $_SERVER['argv'];
array_shift($arguments);
foreach ($arguments as $argument) {
    if (0 === strpos($argument, '--')) {
        // TODO Implement options support
    } else {
        $paths[] = $argument;
    }
}

if (empty($paths)) {
    fatalError("No Test.phlip files to run");
}

try {
    \PHPUnit\TextUI\TestRunner::run(new PhlipScriptTestSuite($paths), ['colors' => 'always']);
} catch (\Exception $e) {
    fatalError($e->getMessage());
}
